export { EditPencil } from './editPencil'
export { PlayInCircle } from './play-in-circle'
export { Bin } from './bin'
export { Close } from './close'
export { Logout } from './log-out'
export { EmailIcon } from './emailIcon/emailIcon'
